apiVersion: v1
kind: ConfigMap
metadata:
  name: aeros-ldap-collector-configmap
data:
  config.ini: |
    ; Configuration file for aerOS LDAP Collector.

    ; Default configuration directives:
    [DEFAULT]
    ; No default directives are used as of now.

    ; (MANDATORY) General directives for the LDAP database:
    [ldap.general]
    ; (MANDATORY) organization_dn (String): DN of the organization which information is to be retrieved.
    organization_dn = dc=example,dc=com

    ; (MANDATORY) Directives for establishing a connection with the LDAP server:
    [ldap.connection]
    ; (MANDATORY) server_endpoint (String): URI where the server is listening for incoming connections or requests.
    ; FORMAT: ldap(s)://<ip_or_fqdn>:<port>
    ; LDAP (unencrypted) port is 389. LDAPS (encrypted) port is 636.
    server_endpoint = ldap://openldap:389

    ; (MANDATORY) use_ssl (Boolean): defines whether or not to use SSL for the connection with the server.
    ; Valid values are True or False.
    use_ssl = False

    ; (MANDATORY) user (String): defines the DN of the LDAP user for connecting and retrieving information.
    user = cn=admin,dc=example,dc=com

    ; (MANDATORY) password (String): password of the LDAP user defined above.
    password = girosadmin

    ; (MANDATORY) max_retries (Integer): defines the maximum number of times the client will try to establish
    ; a connection with the server.
    max_retries = 5

    ; (MANDATORY) timeout (Integer): defines the time (in seconds) to wait between retries while trying to establish
    ; a connection with the server.
    timeout = 5
